
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-runner
  namespace: wordpress-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: runner
  template:
    metadata:
      labels:
        app: runner
    spec:
      serviceAccountName: github-runner-sa
      containers:
      - name: runner
        image: myoung34/github-runner:latest
        env:
        - name: REPO_URL
          value: "https://github.com/ahmed01123376676-cmd/wordpress"
        - name: RUNNER_TOKEN
          value: ""
        - name: RUNNER_NAME
          value: "k8s-runner"
        - name: RUNNER_WORKDIR
          value: "/tmp/runner"