apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: wordpress-ns
data:
  WORDPRESS_DB_HOST: mysql-service
  WORDPRESS_DB_NAME: wordpress
  WORDPRESS_DB_USER: wordpress
  WORDPRESS_DB_PASSWORD: wordpress


