apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql-backup-sa
  namespace: wordpress-ns

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mysql-backup-role
  namespace: wordpress-ns
rules:
- apiGroups: [""]
  resources: ["persistentvolumeclaims", "pods"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mysql-backup-binding
  namespace: wordpress-ns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mysql-backup-role
subjects:
- kind: ServiceAccount
  name: mysql-backup-sa
  namespace: wordpress-ns
  