name: Deploy to Kubernetes

on:
  push:
    branches:
      - main     
    paths:
      - 'k8s/**'
  workflow_dispatch:  

env:
  KUBE_NAMESPACE: wordpress-ns

jobs:
  deploy:
    name: Deploy WordPress to K8s
    runs-on: self-hosted
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.28.0'


    - name: Test K8s Connection
      run: |
        kubectl cluster-info
        kubectl get pods -n wordpress-ns
    

    - name: Deploy Namespace
      run: kubectl apply -f k8s/namespace.yml
    
    - name: Deploy all 
      run: kubectl apply -f k8s/.

    - name: Run Backup CronJob 
      run: |
        kubectl apply -f k8s/backup/rclone-secret.yaml
        kubectl apply -f k8s/backup/mysql-backup-cronjob.yaml


    - name: Verify Deployment
      run: |
        echo "=== Pods Status ==="
        kubectl get pods -n wordpress-ns
        
        echo "=== Services ==="
        kubectl get svc -n wordpress-ns
        
        echo "=== Ingress ==="
        kubectl get ingress -n wordpress-ns
    

      continue-on-error: true
    
